name: CI

on:
  pull_request:   
    branches:
      - main     

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        echo "Running test base"
        pytest tests/unit/test_base.py
        echo "Running test transformations"
        pytest tests/unit/test_transformations.py
        echo "Running test computations"
        pytest tests/unit/test_computations.py
        echo "Running test pipeline"
        pytest tests/unit/test_pipeline.py
